export const endPoint = {
  createagency: "/api/createagency",
  createemployee: "/api/createemployee",
  createcarrier: "/api/createcarrier",
  createenrollemployee: "/api/createenrollemployee",
  createjourney: "/api/createjourney",
  getagencies: "/api/getagencies",
  getemployees: "/api/getemployees",
  getCarriers: "/api/getcarriers",
  getEmployeesByAgency: "/api/getagencyemployees/",
  getagencieswithemployees: "/api/getagencieswithemployees",
  getjourneys: "/api/GetJourneys",
  getjourneybycarrier: "/api/getjourneybycarrier/",
  getjourneybycarrierid: "/api/GetJourneyByCarrierId/",
};
